"use client";
import { ThemeProvider } from "@mui/material";
import { Roboto } from "next/font/google";
import "./global.css";
import { Dark } from "@/themes/dark";
import { ThemeCustome } from "@/themes/themeContext";
import { useContext } from "react";
import App from "./app";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={roboto.className}>
        <ThemeCustome>
          <App>{children}</App>
        </ThemeCustome>
      </body>
    </html>
  );
}
